const BULLET_SIZE = 3;
const CPU_ANGLE_RANDOMNESS_FACTOR = 0.1;
const CPU_LENGTH = 20;
const LAST_SHOT_INDICATOR_SIZE = 2;
const PARTICLE_SIZE_MAX = 4;
const PARTICLE_SIZE_MIN = 1;
const PLANET_RADIUS_MIN = 30;
const PLAYER_LENGTH = 20;
const RENDER_MAX_HEIGHT = 720;
const RENDER_MAX_WIDTH = 1024;
const TRAIL_BULLET_SIZE = 2;
const TRAIL_PARTICLE_SIZE = 1;
const WALL_THICKNESS = 50;

export default {
    BULLET_SIZE,
    CPU_ANGLE_RANDOMNESS_FACTOR,
    CPU_LENGTH,
    LAST_SHOT_INDICATOR_SIZE,
    PARTICLE_SIZE_MAX,
    PARTICLE_SIZE_MIN,
    PLANET_RADIUS_MIN,
    PLAYER_LENGTH,
    RENDER_MAX_HEIGHT,
    RENDER_MAX_WIDTH,
    TRAIL_BULLET_SIZE,
    TRAIL_PARTICLE_SIZE,
    WALL_THICKNESS,
};
