const CPU_VELOCITY_MIN = 4;
const CPU_VELOCITY_MAX = 9;
const EXPLOSION_PARTICLE_COUNT = 10;
const GRAVITATIONAL_CONSTANT = 0.001;
const PLAYER_VELOCITY_FACTOR = 0.01;

export default {
    CPU_VELOCITY_MIN,
    CPU_VELOCITY_MAX,
    EXPLOSION_PARTICLE_COUNT,
    GRAVITATIONAL_CONSTANT,
    PLAYER_VELOCITY_FACTOR,
};
